CREATE TABLE QUERY (
	id INT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description TEXT,
	url TEXT NOT NULL,
	query TEXT NOT NULL,
	project_id INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (project_id) REFERENCES PROJECT(id) ON DELETE CASCADE
);
